USE ZEPTO_SQL_PROJECT;
SELECT * FROM zepto_v2;

-- DATA EXPLORATION

-- COUNT OF ROWS
SELECT COUNT(*) FROM zepto_v2;

-- CHECK NULL values
SELECT * FROM zepto_v2
WHERE CATEGORY IS NULL
OR
NAME IS NULL
OR MRP IS NULL
OR DISCOUNTPERCENT IS NULL
OR AVAILABLEQUANTITY IS NULL
OR DISCOUNTEDSELLINGPRICE IS NULL
OR WEIGHTINGMS IS NULL
OR OUTOFSTOCK IS NULL
OR QUANTITY IS NULL;
-- NO NULL values

-- DIFFERENT PRODUCT CATEGORY
SELECT DISTINCT CATEGORY 
FROM zepto_v2
ORDER BY CATEGORY;

-- ADDING NEW ID COLUMN
ALTER TABLE zepto_v2
ADD COLUMN ID INT AUTO_INCREMENT PRIMARY KEY;

-- CHECK PRODUCT IN STOCK 
SELECT OUTOFSTOCK,COUNT(ID)
FROM zepto_v2
GROUP BY OUTOFSTOCK;

-- PRODUCT NAME PRESENT MULTIPLETIMES
SELECT NAME,COUNT(ID)  FROM zepto_v2
GROUP BY NAME
HAVING COUNT(ID)>1
ORDER BY COUNT(ID) DESC;

-- DATA CLEANING

-- PRODUCT WITH PRICE=0
SELECT * FROM zepto_v2
WHERE MRP=0 OR discountedSellingPrice=0;

DELETE FROM zepto_v2
WHERE MRP=0;

-- CONVERT PAISE TO RUPEES
UPDATE zepto_v2
SET mrp=mrp/100,
discountedSellingPrice=discountedSellingPrice/100;

SELECT * FROM zepto_v2;

-- FIND THE TOP 10 BEST-VALUE PRODUCTS BASED ON THE DISCOUNTE PERCENTAGE.
SELECT DISTINCT name,mrp,discountPercent from zepto_v2
ORDER BY discountPercent DESC
LIMIT 10;

-- WHAT ARE THE PRODUCTS WITH HIGH MRP BUT OUT OF STOCK
SELECT DISTINCT name,mrp,outOfStock from zepto_v2
WHERE outOfStock="TRUE" AND mrp>300
ORDER BY mrp DESC;

-- CALCULATE ESTIMATED REVENUE FOR EACH CATEGORY
SELECT Category, SUM(discountedSellingPrice*availableQuantity) AS Revenue FROM zepto_v2
GROUP BY Category
ORDER BY Revenue;

-- FIND ALL PRODUCTS WHERE MRP IS GREATER THAN RS 500 AND DISCOUNT IS LESS THAN 10%;
SELECT DISTINCT name, mrp,discountPercent From zepto_v2
WHERE  mrp>500 AND discountPercent<10
ORDER BY mrp DESC,discountPercent  DESC;

-- IDENTIFY THE TOP 5 CATEGORIES OFFERING THE HIGHEST AVERAGE DISCOUNT PERCENTAGE.
SELECT DISTINCT Category,ROUND(AVG(discountPercent),2) AS AVG_DISCOUNT FROM zepto_v2
GROUP BY Category
ORDER BY AVG_DISCOUNT DESC;

-- FIND THE PRICE PER GRAM FOR PRODUCTS ABOVE 100g AND SORT BY BEST VALUE
SELECT DISTINCT name,weightInGms,discountedSellingPrice,ROUND((discountedSellingPrice/weightInGms),2)AS PRICE_PER_Gms
FROM zepto_v2
WHERE weightInGms>100
ORDER BY PRICE_PER_Gms;

-- GROUP THE PRODUCTS INTO CATEGORIES LIKE LOW,MEDIUM,BULK
SELECT DISTINCT name,weightInGMS,
CASE WHEN weightInGms<1000 Then 'LOW'
     WHEN weightInGms<5000 Then 'Medium'
     ELSE 'Bulk'
     END AS weight_category
FROM zepto_v2;

-- WHAT IS TOTAL INVENTORY WEIGHT PER CATEGORY
SELECT category,
       SUM(weightInGms * availableQuantity) AS total_inventory_weight
FROM zepto_v2
GROUP BY category
ORDER BY total_inventory_weight DESC;
